// <auto-generated />
using System;
using BS_KretaProjekt.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BS_KretaProjekt.Migrations
{
    [DbContext(typeof(KretaDbContext))]
    [Migration("20260429110800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Diak", b =>
                {
                    b.Property<int>("diak_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("diak_id"));

                    b.Property<string>("diak_nev")
                        .HasColumnType("text");

                    b.Property<string>("emailcim")
                        .HasColumnType("text");

                    b.Property<string>("lakcim")
                        .HasColumnType("text");

                    b.Property<int?>("osztaly_id")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("szuletesi_datum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("szuloneve")
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("diak_id");

                    b.HasIndex("osztaly_id");

                    b.HasIndex("user_id");

                    b.ToTable("Diakok");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Hianyzas", b =>
                {
                    b.Property<int>("hianyzas_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("hianyzas_id"));

                    b.Property<int>("hianyzottorakszama")
                        .HasColumnType("integer");

                    b.HasKey("hianyzas_id");

                    b.ToTable("Hianyzasok");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Jegy", b =>
                {
                    b.Property<int>("jegy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("jegy_id"));

                    b.Property<DateTimeOffset>("datum")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("diak_id")
                        .HasColumnType("integer");

                    b.Property<int>("ertek")
                        .HasColumnType("integer");

                    b.Property<int>("tanar_id")
                        .HasColumnType("integer");

                    b.Property<int>("tantargy_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("updatedatum")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("jegy_id");

                    b.HasIndex("diak_id");

                    b.HasIndex("tanar_id");

                    b.HasIndex("tantargy_id");

                    b.ToTable("Jegyek");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Orarend", b =>
                {
                    b.Property<int>("orarend_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("orarend_id"));

                    b.Property<int>("nap")
                        .HasColumnType("integer");

                    b.Property<int>("ora")
                        .HasColumnType("integer");

                    b.Property<int>("osztaly_id")
                        .HasColumnType("integer");

                    b.Property<int>("tanar_id")
                        .HasColumnType("integer");

                    b.Property<int>("tantargy_id")
                        .HasColumnType("integer");

                    b.HasKey("orarend_id");

                    b.HasIndex("osztaly_id");

                    b.HasIndex("tanar_id");

                    b.HasIndex("tantargy_id");

                    b.ToTable("Orarendek");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Osztaly", b =>
                {
                    b.Property<int>("osztaly_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("osztaly_id"));

                    b.Property<string>("osztaly_nev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("osztaly_id");

                    b.HasIndex("osztaly_nev")
                        .IsUnique();

                    b.ToTable("Osztalyok");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Tanar", b =>
                {
                    b.Property<int>("tanar_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tanar_id"));

                    b.Property<string>("szak")
                        .HasColumnType("text");

                    b.Property<string>("tanar_nev")
                        .HasColumnType("text");

                    b.Property<int?>("tantargy_id")
                        .HasColumnType("integer");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("tanar_id");

                    b.HasIndex("tantargy_id");

                    b.HasIndex("user_id");

                    b.ToTable("Tanarok");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Tantargy", b =>
                {
                    b.Property<int>("tantargy_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tantargy_id"));

                    b.Property<string>("tantargy_nev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("tantargy_id");

                    b.HasIndex("tantargy_nev")
                        .IsUnique();

                    b.ToTable("Tantargyok");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("belepesnev")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("jelszo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.HasIndex("belepesnev")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Uzenet", b =>
                {
                    b.Property<int>("uzenet_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("uzenet_id"));

                    b.Property<string>("cim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("fogado_id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("kuldesidopontja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("tartalom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("uzenet_id");

                    b.HasIndex("fogado_id");

                    b.HasIndex("user_id");

                    b.ToTable("Uzenetek");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Diak", b =>
                {
                    b.HasOne("BS_KretaProjekt.Persistence.Osztaly", "Osztaly")
                        .WithMany()
                        .HasForeignKey("osztaly_id");

                    b.HasOne("BS_KretaProjekt.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osztaly");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Jegy", b =>
                {
                    b.HasOne("BS_KretaProjekt.Persistence.Diak", "Diak")
                        .WithMany("jegyek")
                        .HasForeignKey("diak_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BS_KretaProjekt.Persistence.Tanar", "Tanar")
                        .WithMany("jegyek")
                        .HasForeignKey("tanar_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BS_KretaProjekt.Persistence.Tantargy", "Tantargy")
                        .WithMany()
                        .HasForeignKey("tantargy_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diak");

                    b.Navigation("Tanar");

                    b.Navigation("Tantargy");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Orarend", b =>
                {
                    b.HasOne("BS_KretaProjekt.Persistence.Osztaly", "Osztaly")
                        .WithMany("Orarend")
                        .HasForeignKey("osztaly_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BS_KretaProjekt.Persistence.Tanar", "Tanar")
                        .WithMany("Orarend")
                        .HasForeignKey("tanar_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BS_KretaProjekt.Persistence.Tantargy", "Tantargy")
                        .WithMany("Orarend")
                        .HasForeignKey("tantargy_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Osztaly");

                    b.Navigation("Tanar");

                    b.Navigation("Tantargy");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Tanar", b =>
                {
                    b.HasOne("BS_KretaProjekt.Persistence.Tantargy", "Tantargy")
                        .WithMany()
                        .HasForeignKey("tantargy_id");

                    b.HasOne("BS_KretaProjekt.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tantargy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Uzenet", b =>
                {
                    b.HasOne("BS_KretaProjekt.Persistence.User", "Fogado")
                        .WithMany()
                        .HasForeignKey("fogado_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BS_KretaProjekt.Persistence.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fogado");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Diak", b =>
                {
                    b.Navigation("jegyek");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Osztaly", b =>
                {
                    b.Navigation("Orarend");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Tanar", b =>
                {
                    b.Navigation("Orarend");

                    b.Navigation("jegyek");
                });

            modelBuilder.Entity("BS_KretaProjekt.Persistence.Tantargy", b =>
                {
                    b.Navigation("Orarend");
                });
#pragma warning restore 612, 618
        }
    }
}
